default_language_version:
  python: python3.11

default_stages: [commit, manual]

exclude: ^(gunicorn_config.py)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: end-of-file-fixer
      - id: debug-statements
      # - id: no-commit-to-branch
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
